import Koa from 'koa';
import serve from 'koa-static';
import { h } from 'preact';
import renderToString from 'preact-render-to-string';
import { extractCss, setPragma } from 'goober';
import { JSDOM } from 'jsdom';
import App from '../src/App';
import { mainGlobalStyles } from '../src/styles/main'; 

const jsdom = new JSDOM("<!doctype html><html><body><div>Hello World</div></body></html>");
const { window } = jsdom;

// Store away globals needed in node
(global as any).window = window;
(global as any).document = window.document;

setPragma(h);

/**
 * Injected by webpack.DefinePlugin
 */
declare const ASSETS_MANIFEST_PATH: string;
declare const STATIC_ASSETS_PATH: string;

const app = new Koa();
const webpackManifest = require(ASSETS_MANIFEST_PATH);
const mainJs = webpackManifest.main.js;

app.use(serve(STATIC_ASSETS_PATH, {
  index: 'NO_INDEX_FILE_ALLOWED.html',
})); // serve the static assets generated by snowpack build

app.use(async (ctx) => {
  // need to be called for every request
  const gooberContext = { target: document.createElement('div') };

  mainGlobalStyles(gooberContext); 
  const markup = renderToString(<App name="SSR" gooberContext={gooberContext} />);

  // simulate asynchronous rendering, for example, maybe we are using react-apollo `renderToStringWithData()`
  // Because goober use a single "sheet" for SSR, this will not work properly.
  // Only the first finished request will get the style from extractCss();
  await (async () => {
    return new Promise(resolve => {
      setTimeout(() => {
        resolve();
      }, 3000)
    })
  })();

  // @ts-expect-error
  const style = extractCss(gooberContext.target);

  console.log({style})

  ctx.body = `
    <html>
    <head>
      <meta charset="utf-8" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Web site created using create-snowpack-app" />
      <title>SSR - Snowpack preact</title>
      <style>${style}</style>
    </head>
    <body>
      <div id="root">${markup}</div>
      <script defer src="${mainJs}"></script>
    </body>
    </html>
  `
})

app.listen(8001, () => {
  console.log('Koa server listening on port 8001')
});
